# Generated by Django 3.2 on 2021-06-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_compteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.FileField(blank=True, default='images/photo.png', null=True, upload_to='Contact_file'),
        ),
    ]
