# Generated by Django 3.2 on 2021-06-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20210612_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteuser',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='compteUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to='contact.compteuser'),
        ),
    ]
