# Generated by Django 3.2 on 2021-06-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contact_compteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='photo',
            field=models.FileField(blank=True, default='images/photo.png', null=True, upload_to='CompteUser_file'),
        ),
    ]
