# Generated by Django 3.2 on 2021-06-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_compteuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='photo',
            field=models.FileField(blank=True, default='photo.png', null=True, upload_to='CompteUser_file'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.FileField(blank=True, default='photo.png', null=True, upload_to='Contact_file'),
        ),
    ]
