# Generated by Django 3.2 on 2021-06-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20210613_0754'),
        ('contact', '0010_auto_20210613_2027'),
    ]

    operations = [
    ]
