# Generated by Django 3.2 on 2021-06-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_merge_0010_auto_20210613_0754_0010_auto_20210613_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='telephone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
